### ISSUE TITLE
Bosh Backup & Restore SDK Cannot Restore Vanilla RDS Backup

### ISSUE THREAD

**Issue by pivotal-mp** [cloudfoundry-incubator/backup-and-restore-sdk-release#13]
The BOSH team recently began having BBR tests fail in our pipeline due to a
MySQL RDS backup/restore test that failed with the error message "ERROR 1227
(42000) at line 18: Access denied; you need (at least one of) the SUPER
privilege(s) for this operation ".  Careful investigation showed that the line
that was causing the failure was trying to unset GTID for the restore session
by running `SET @@SESSION.SQL_LOG_BIN=0;`.  It turns out that AWS (recently
enabled GTID for RDS)[https://forums.aws.amazon.com/ann.jspa?annID=6203] in
early October of 2018 which is likely what began our test failures.  The
implication of this change is that a vanilla MySQL RDS is created with a user
that has permission to run `mysqldump` but cannot use that SQL dump file to
restore since it needs SUPER privileges to unset GTID for the restore session.
There are four ways to work around this that we have:

1. Change the BBR SDK to use `--set-gtid-purged=OFF` [[1]](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_set-gtid-purged)
2. Use an older version of MySQL that does not support GTID for our own tests (5.5 seems to work)
3. Change our RDS parameter group to set `gtid-mode` to `OFF` (default with no DB replica and no backups for us is `OFF_PERMISSIVE` which results in this failure anyway)
4. Switch from using RDS to using a VM running MySQL and use the root user to run BBR which should be able to run this sort of command anyway.

-- @pivotal-mp && @jaresty from the BOSH team

**Comment by alamages** [comment]
Hello @pivotal-mp and @jaresty,

Thanks for the debug info in this issue. We would like to reproduce the issue as well before coming up with a solution. I am a little confused though with what version of mysql we can reproduce this. To what mysql version does Vanilla RDS refers to? Thanks

**Comment by pivotal-mp** [comment]
Hello,

AWS enabled a MySQL 5.6/5.7 feature called Global Transaction Identifier
(GTID), so now any default RDS MySQL will use this feature out of the box.
That's what we meant by "Vanilla RDS".

Best,
Max

On Wed, Oct 24, 2018 at 6:35 AM, Emmanouil Kiagias <notifications@github.com

**Comment by MirahImage** [comment]
Hi @pivotal-mp, 

Thanks for finding this issue. We have chosen to go with the first implementation, passing the `--set-gtid-purged=OFF` flag to `mysqldump` for MySQL 5.6+. Once the fix passes our pipeline, we'll cut a new version of the SDK.

Best,
Mirah & @alamages

**Comment by pivotal-mp** [comment]
Awesome, thanks :)

**Comment by glestaris** [comment]
Hey @pivotal-mp, we just released [v1.11.0](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/releases/tag/v1.11.0) of the SDK. I am closing this issue. Feel free to reopen if the problem persists.
