### ISSUE TITLE
Unable to backup Postgres 11.1 due to parsing errors

### ISSUE THREAD

**Issue by cirocosta** [cloudfoundry-incubator/backup-and-restore-sdk-release#14]
Hey,

@youssb and I were trying to perform backups of Concourse (using Postgres 11.1 - [release v33](https://bosh.io/releases/github.com/cloudfoundry/postgres-release?all=1#v33)) and running `bbr deploy [...] backup [...]` returned the following error:

```
2018/12/27 18:05:39 Unable to check version of Postgres: could not parse semver: "11.1" - exit code 1
```

Our guess is that there's a parsing issue happening under `version_detector.go`:

https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/blob/c735374dd73f26932afc39510bc0156902c1ad36/src/github.com/cloudfoundry-incubator/database-backup-restore/postgres/version_detector.go#L28-L30

Looking at `ci`, there's no v33 (pg 11.1) there, so I guess that's because it's supposed to not be supported yet - is that right? 

Please let me know if there's any way that we can help 😁 

Thanks very much!

**Comment by ChunyiLyu** [comment]
Hi @cirocosta, You are totally right. We do not support Postgres v11 in our sdk release currently.  Is Postgres v11 the default db in current concourse?

Cheers,
Chunyi

**Comment by cirocosta** [comment]
Hey @ChunyiLyu ,

The Concourse release doesn't specify an upper limit on the version, just a lower (9.5), so in our pipelines, we always test against the latest version that's out there (v11 right now).

This is currently not a blocker for us, but it'd be nice if we could have that in - we're improving our BBR support right now.

Thanks!

**Comment by glestaris** [comment]
@cirocosta thanks for reporting. Prioritising for this week's IPM.

**Comment by gmrodgers** [comment]
Support introduced in https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/releases/tag/v1.15.0
