### ISSUE TITLE
MySQL BBR restore doesn't print any output during a successful run

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry-incubator/backup-and-restore-sdk-release#4]
On a successful run of the BBR `restore` script with a MySQL database, no output is printed to STDOUT/ERR. The only way to tell it succeeded is to check the exit code. Would be nice to see confirmation that the restore went as expected.

Also, while the `backup` script does print plenty of output, it is not obvious whether it was successful or not.

Thanks!

**Comment by edwardecook** [comment]
Hi @tcdowney this should was accepted at the end of September, not entirely sure how the issue stayed open but it should now be fixed. Feel free to reopen this if there are any further issues.
